version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    ports:
      - "8081:8081"
      - "1337:1337"
    environment:
      - NODE_ENV=development
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge
