name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: app/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('app/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: |
        cd app
        npm install

    - name: Build for web
      run: |
        cd app
        npx expo export --platform web
      env:
        NODE_ENV: production
        EXPO_PUBLIC_URL: /Ecommerce

    - name: Fix asset paths for GitHub Pages
      run: |
        cd app/dist
        # Actualizar todas las referencias en el index.html para que apunten al subdirectorio correcto
        sed -i 's|="/_expo/|="/Ecommerce/_expo/|g' index.html
        sed -i 's|src="/_expo/|src="/Ecommerce/_expo/|g' index.html
        sed -i 's|href="/_expo/|href="/Ecommerce/_expo/|g' index.html

        # Corregir rutas de assets (imágenes, fuentes, etc.)
        sed -i 's|="/assets/|="/Ecommerce/assets/|g' index.html
        sed -i 's|src="/assets/|src="/Ecommerce/assets/|g' index.html
        sed -i 's|href="/assets/|href="/Ecommerce/assets/|g' index.html

        # Corregir favicon específicamente
        sed -i 's|rel="icon" href="[^"]*"|rel="icon" href="/Ecommerce/assets/assets/images/icon.png"|g' index.html
        sed -i 's|rel="shortcut icon" href="[^"]*"|rel="shortcut icon" href="/Ecommerce/assets/assets/images/icon.png"|g' index.html

        # También corregir referencias en archivos JS
        find . -name "*.js" -type f -exec sed -i 's|"/_expo/|"/Ecommerce/_expo/|g' {} \;
        find . -name "*.js" -type f -exec sed -i "s|'/_expo/|'/Ecommerce/_expo/|g" {} \;
        find . -name "*.js" -type f -exec sed -i 's|"/assets/|"/Ecommerce/assets/|g' {} \;
        find . -name "*.js" -type f -exec sed -i "s|'/assets/|'/Ecommerce/assets/|g" {} \;

        # Corregir referencias en archivos CSS si existen
        find . -name "*.css" -type f -exec sed -i 's|url(/assets/|url(/Ecommerce/assets/|g' {} \;
        find . -name "*.css" -type f -exec sed -i 's|url("\/assets/|url("/Ecommerce/assets/|g' {} \;

    - name: Setup SPA routing for GitHub Pages
      run: |
        cd app/dist
        # Agregar base tag al index.html para routing correcto
        sed -i 's|<head>|<head><base href="/Ecommerce/">|g' index.html

        # Crear 404.html para SPA routing
        cp index.html 404.html

        # Crear script de routing en archivo separado
        cat > routing-fix.js << 'EOF'
        // Fix routing for GitHub Pages
        if (window.location.pathname.startsWith("/Ecommerce") && !window.location.pathname.endsWith("/")) {
          if (window.location.pathname === "/Ecommerce") {
            window.history.replaceState(null, "", "/Ecommerce/");
          }
        }
        EOF

        # Insertar el script antes del cierre del body
        sed -i 's|</body>|<script src="./routing-fix.js"></script></body>|g' index.html    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./app/dist

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
