name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        registry-url: 'https://registry.npmjs.org'

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: app/node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('app/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: |
        cd app
        npm install

    - name: Build for web
      run: |
        cd app
        npx expo export --platform web --output-dir dist --public-url /Ecommerce
      env:
        NODE_ENV: production

    - name: Fix asset paths
      run: |
        cd app/dist
        # Crear directorio _expo en el lugar correcto
        mkdir -p Ecommerce/_expo
        # Mover archivos _expo al subdirectorio correcto
        if [ -d "_expo" ]; then
          cp -r _expo/* Ecommerce/_expo/
        fi
        # Actualizar referencias en index.html
        sed -i 's|/_expo/|/Ecommerce/_expo/|g' index.html

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./app/dist

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
